onedrive_pos/auth_pos/urls.py
from django.urls import path
from . import views
app_name = 'auth_pos'  # Define the namespace for URL reversal


urlpatterns = [
    #  authentication routes
    path('register/', views.register, name='register'),
    path('', views.login, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('lock_screen/', views.lock_screen, name='lock_screen'),
    path('admin_dashboard', views.admin_dashboard, name='admin_dashboard'),
    path('manager_dashboard', views.manager_dashboard, name='manager_dashboard'),
    path('cashier_dashboard', views.cashier_dashboard, name='cashier_dashboard'),
    path('loader/', views.loader_view, name='loader'),
]

onedrive_pos/onedrive_pos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    
    path('admin/', admin.site.urls),
    path('', include('auth_pos.urls')),
    path('products/', include('products.urls')),
    path('branches/', include('branches.urls')),
    path('pos/', include('pos.urls')),
    path('staff/', include('staff.urls')),
    path('profile/', include('user_profile.urls'))


]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onedrive_pos/pos/urls.py
from django.urls import path
from . import views

app_name = 'pos'

urlpatterns = [
    path('create/', views.create_sale, name='create_sale'),
    path('list/', views.sale_list, name='sale_list'),
    path('view/<int:sale_id>/', views.view_sale, name='view_sale'),
    path('search-products/', views.search_products, name='search_products'),
    path('add-product-to-sale/', views.add_product_to_sale, name='add_product_to_sale'),
    path('remove-product-from-sale/', views.remove_product_from_sale, name='remove_product_from_sale'),
    path('complete-sale/', views.complete_sale, name='complete_sale'),
    path('sales/list/', views.sales_list_view, name='sales'),
    
  
]

onedrive_pos/pos/models.py
from django.db import models
from products.models import Product
from staff.models import Employee
from branches.models import Branch



class Sale(models.Model):
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    cashier = models.ForeignKey(Employee, on_delete=models.CASCADE,null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
  

    def __str__(self):
        return f'Sale {self.id}' 


class SaleItem(models.Model):
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE)
    product = models.ForeignKey(Product ,related_name='sale_items', on_delete=models.CASCADE)
    quantity = models.IntegerField()
      # Assuming quantity is always positive
    price = models.DecimalField(max_digits=10, decimal_places=2)
    total = models.DecimalField(max_digits=10, decimal_places=2, default=0)

onedrive_pos/pos/forms.py
# forms.py
from django import forms

class SaleFilterForm(forms.Form):
    search = forms.CharField(required=False)
    date_filter = forms.ChoiceField(required=False, choices=[
        ('', 'All dates'),
        ('today', 'Today'),
        ('yesterday', 'Yesterday'),
        ('this_week', 'This week'),
        ('last_week', 'Last week'),
    ])
    money_filter = forms.ChoiceField(required=False, choices=[
        ('', 'All amounts'),
        ('high_to_low', 'High to low'),
        ('low_to_high', 'Low to high'),
    ])

onedrive_pos/pos/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Sale, SaleItem
from products.models import Product
from branches.models import Branch
from django.http import JsonResponse, HttpResponse
from django.template.loader import render_to_string
from django.db import transaction
from django.db.models import F
from xhtml2pdf import pisa # type: ignore
from django.http import HttpResponse
from django.template.loader import get_template
import datetime
from datetime import date
from staff.models import *
from django.db.models import Q
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .forms import SaleFilterForm




@login_required
def sale_list(request):
    active_nav_item = 'pos'
    sales = Sale.objects.filter(branch=request.user.employee.branch)
    return render(request, 'pos/sale_list.html', {'sales': sales,'active_nav_item':active_nav_item})

@login_required
def view_sale(request, sale_id):
    active_nav_item = 'pos'
    sale = Sale.objects.get(id=sale_id)
    return render(request, 'pos/view_sale.html', {'sale': sale,'active_nav_item':active_nav_item})


@login_required
def create_sale(request):
    active_nav_item = 'pos'
    today = date.today()
    employee = Employee.objects.get(user=request.user)
    products = Product.objects.filter(branch=request.user.employee.branch)
    branch = request.user.employee.branch
    if request.method == 'POST':
        # Create a new sale
        sale = Sale.objects.create(branch=request.user.employee.branch, total_amount=0, cashier_id=request.user.id)

        # Render the updated sale table and total amount as HTML
        sale_table_html = render_to_string('pos/sale_table.html', {'sale': sale})

        return JsonResponse({'sale_table': sale_table_html, 'total_amount': 0, 'sale_id': sale.id})
    else:
        products = Product.objects.filter(branch=request.user.employee.branch)
        categories = Product.objects.filter(branch=request.user.employee.branch).values('category__name').distinct()
        sale_id = request.GET.get('sale_id')

        if sale_id:
            sale_items = SaleItem.objects.filter(sale__id=sale_id)  # Get the sale items for the current sale
            sale = Sale.objects.get(id=sale_id)  # Get the current sale

            # Calculate the total for each sale item
            for item in sale_items:
                item.total = item.quantity * item.product.price
                item.save()

            # Calculate the total amount
            total_amount = sum(item.total for item in sale_items)
              # Calculate the change
            
        else:
            sale_items = []  # Initialize an empty list for sale items
            sale = Sale.objects.create(branch=request.user.employee.branch, total_amount=0, cashier_id=request.user.id)
            total_amount = 0

        return render(request, 'pos/create_sale.html', {'products': products, 'sale_items': 
                                                        sale_items,'sale':sale, 'sale_id': sale.id, 'total_amount': 
                                                        total_amount,'today':today,'employee':employee,'branch':branch, 'active_nav_item':active_nav_item,
                                                        'categories': categories})


@login_required
def search_products(request):
    active_nav_item = 'pos'
    search_term = request.GET.get('search_term', '')
    category = request.GET.get('category', '')
    branch = request.user.employee.branch
    page = request.GET.get('page', 1)

    if category:
        products = Product.objects.filter(category__name=category, branch=branch)
    else:
        products = Product.objects.filter(branch=branch)

    if search_term:
        products = products.filter(
            Q(name__icontains=search_term) |
            Q(description__icontains=search_term) |
            Q(make__icontains=search_term) |
            Q(model__icontains=search_term) |
            Q(price__icontains=search_term)
        )

    paginator = Paginator(products, 5)  # Show 10 products per page
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    results = []
    for product in products:
        results.append({
            'id': product.id,
            'name': product.name,
            'description': product.description,
            'make': product.make,
            'model': product.model,
            'quantity': product.quantity,
            'price': product.price,
            'category': product.category.name,
        })

    return JsonResponse({
        'active_nav_item':active_nav_item,
        'results': results,
        'has_previous': products.has_previous(),
        'has_next': products.has_next(),
        'previous_page_number': products.previous_page_number() if products.has_previous() else None,
        'next_page_number': products.next_page_number() if products.has_next() else None,
    }, safe=False)



@login_required
def complete_sale(request):
    today = date.today()

    if request.method == 'POST':
        sale_id = request.POST.get('sale_id')
        amount_paid = float(request.POST.get('amount_paid'))
        

        try:
            sale = Sale.objects.get(id=sale_id)
        except Sale.DoesNotExist:
            return JsonResponse({'error': 'Sale does not exist'})

        # Calculate the total amount of the sale
        total_amount = sale.total_amount
        total_amount = sum(item.quantity * item.price for item in SaleItem.objects.filter(sale=sale))

        # Update the product quantity
        for item in sale.saleitem_set.all():
            product = item.product
            print("Before update:", product.quantity)
            product.quantity -= item.quantity
            print("Product quantity after calculation:", product.quantity)
            product.save()
            print("After update:", product.quantity)

        # Calculate the change
        change = amount_paid - float(total_amount)

        # Create a new sale
        new_sale = Sale.objects.create(branch=request.user.employee.branch, total_amount=0, cashier_id=request.user.id)

        # Render the receipt as HTML
        receipt_html = render_to_string('pos/receipt.html', {'sale': sale, 'sale_items': sale.saleitem_set.all(), 'amount_paid': amount_paid, 'change': change,'today':today})

        return JsonResponse({'message': 'Sale completed successfully', 'change': change, 'new_sale_id': new_sale.id, 'receipt_html': receipt_html})
    else:
        return HttpResponse('Invalid request method')


@login_required
def add_product_to_sale(request):
    if request.method == 'POST':
        product_id = request.POST.get('product_id')
        quantity = int(request.POST.get('quantity'))
        sale_id = request.POST.get('sale_id')

        try:
            sale = Sale.objects.get(id=sale_id)
        except Sale.DoesNotExist:
            return JsonResponse({'error': 'Sale does not exist'})

        product = Product.objects.get(id=product_id)

        # Check if product is already in the sale
        if SaleItem.objects.filter(sale=sale, product=product).exists():
            sale_item = SaleItem.objects.get(sale=sale, product=product)
            sale_item.quantity += quantity
            sale_item.save()
        else:
            SaleItem.objects.create(sale=sale, product =product, quantity=quantity, price=product.price)

        # Recalculate the total amount
        sale.total_amount = sum(item.quantity * item.price for item in SaleItem.objects.filter(sale=sale))
        sale.save()

        # Render the updated sale table and total amount as HTML
        sale_items = SaleItem.objects.filter (sale=sale)
        sale_table_html = render_to_string('pos/sale_table.html', {'sale': sale, 'sale_items': sale_items})

        return JsonResponse({'sale_table': sale_table_html, 'total_amount': sale.total_amount})
    else:
        return HttpResponse('Invalid request method')



@login_required
def remove_product_from_sale(request):
    if request.method == 'POST':
        product_id = request.POST.get('product_id')
        sale_id = request.POST.get('sale_id')

        try:
            sale = Sale.objects.get(id=sale_id)
        except Sale.DoesNotExist:
            return JsonResponse({'error': 'Sale does not exist'})

        product = Product.objects.get(id=product_id)

        # Check if product is in the sale
        if SaleItem.objects.filter(sale=sale, product=product).exists():
            sale_item = SaleItem.objects.get(sale=sale, product=product)
            sale_item.delete()

            # Recalculate the total amount
            sale.total_amount = sum(item.quantity * item.price for item in SaleItem.objects.filter(sale=sale))
            sale.save()

            # Render the updated sale table and total amount as HTML
            sale_items = SaleItem.objects.filter(sale=sale)
            sale_table_html = render_to_string('pos/sale_table.html', {'sale': sale, 'sale_items': sale_items})

            return JsonResponse({'sale_table': sale_table_html, 'total_amount': sale.total_amount})
        else:
            return JsonResponse({'error': 'Product is not in the sale'})
    else:
        return HttpResponse('Invalid request method')
  

       

@login_required
def sales_list_view(request):

    active_nav_item = 'sales'
    sales = Sale.objects.all()

    # Search feature
    search_query = request.GET.get('search')
    if search_query:
        sales = sales.filter(product__name__icontains=search_query)

    # Filtering by date
    date_filter = request.GET.get('date_filter')
    if date_filter == 'today':
        sales = sales.filter(date_created=request.date.today())
    elif date_filter == 'yesterday':
        sales = sales.filter(date_created=request.date.today() - datetime.timedelta(days=1))

onedrive_pos/templates/pos/receipt.html
<!-- receipt.html -->
{% load static %}
<div class="receipt">
  <div class="row">
    <div class="receipt-main ">
      <div class="row">
        <div class="receipt-header">
          <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="receipt-left">
              <img src="{% static 'img/logo.png' %}" alt="Logo" width="50" height="50">
            </div>
          </div>
          <div class="col-xs-6 col-sm-6 col-md-6 text-right">
            <div class="receipt-right">
              <h5>OneDrive.</h5>
              <p>+263 718910821<i class="fa fa-phone"></i></p>
              <p>info@onedrive.com <i class="fa fa-envelope-o"></i></p>
              <p>Harare, Zimbabwe <i class="fa fa-location-arrow"></i></p>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="receipt-header receipt-header-mid">
          <div class="col-xs-8 col-sm-8 col-md-8 text-left">
            <div class="receipt-right">
              <h5>Sale ID: <small>{{ sale.id }}</small></h5>
              <p><b>Date :</b>{{ sale.date_created }}</p>
              <p><b>Cashier:</b>{{employee.user.first_name}} {{employee.user.last_name}}</p>
            </div>
          </div>
          <div class="col-xs-4 col-sm-4 col-md-4">
            <div class="receipt-left">
              <h1>Receipt</h1>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="table">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>Product</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Total</th>
              </tr>
            </thead>
            <tbody>
              {% for item in sale_items %}
              <tr>
                <td>{{ item.product.name }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.total }}</td>
                <td><i class="fa fa-inr"></i>{{ item.product.price }}</td>
              </tr>
              {% endfor %}
              <tr>
                <td colspan="3" class="text-right">
                  <p>
                    <strong>Total Amount: {{ sale.total_amount }}</strong>
                  </p>
                  <p>
                    <strong>Amount Paid: {{ amount_paid }}</strong>
                  </p>
                  <p>
                    <strong>Change: {{ change }}</strong>
                  </p>
                </td>
              </tr>
              <tr>
                <td colspan="3" class="text-right">
                  <h2><strong>Total: </strong></h2>
                </td>
                <td class="text-left text-danger">
                  <h2><strong><i class="fa fa-inr"></i>{{ sale.total_amount }}</strong></h2>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <div class="row">
        <div class="receipt-header receipt -header-mid receipt-footer">
          <div class="col-xs-8 col-sm-8 col-md-8 text-left">
            <div class="receipt-right">
              <p><b>Date :</b>{{ today }}</p>
              <h5 style="color: rgb(140, 140, 140);">Thank you for doing business with us.!</h5>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
    .receipt {
        overflow-y: auto;
        font-family: 'Open Sans', sans-serif;
        font-size: 16px; /* Adjusted font size for modal */
        line-height: 1.5;
        color: #333;
        background-color: #f9f9f9;
        padding: 20px; /* Adjusted padding for modal */
        border: none; /* Removed border to fit within modal */
        border-radius: 0; /* Removed border radius to fit within modal */
        box-shadow: none; /* Removed box shadow to fit within modal */
      }
      
      .receipt-main {
        background-color: #fff;
        padding: 20px; /* Adjusted padding for modal */
      }
      
      .receipt-header {
        background-color: #f9f9f9;
        padding: 5px; /* Adjusted padding for modal */
        border-bottom: 1px solid #ddd;
        align-content: center;
      }
      
      .receipt-header-mid {
        background-color: #fff;
        padding: 5px; /* Adjusted padding for modal */
        border-bottom: 1px solid #ddd;
      }
      
      .receipt-footer {
        background-color: #f9f9f9;
        padding: 15px; /* Adjusted padding for modal */
        border-top: 1px solid #ddd;
      }
      
      .receipt-left {
        float: left;
      }
      .receipt-right{
        float: right;

      }
      
     
      
      .table-responsive {
        overflow-x: auto;
      }
      
      .table-bordered {
        border: 1px solid #ddd;
      }
      
      .table-bordered th, .table-bordered td {
        border: 1px solid #ddd;
        padding: 15px; /* Adjusted padding for modal */
      }
      
      .text-danger {
        color: #d9534f;
      }
      
      .fa-inr {
        font-size: 20px; /* Adjusted font size for modal */
        margin-right: 10px;
      }
      
      h1, h2, h3, h4, h5 {
        font-size: 15px; /* Adjusted font size for modal */
        margin-bottom: 2px;
      }
      .text-danger {
        color: #d9534f;
      }
      
      .fa-inr {
        font-size: 12px;
        margin-right: 5px;
      }

</style>

onedrive_pos/templates/pos/sale_list.html
{% extends 'dashboard/cashier_dashboard.html' %}

{% block content %}
    <!-- pagetitle -->
    <div class="pagetitle">
        <h1 class="h5 text-md font-weight-bold text-primary text-uppercase mb-1">Sales</h1>
        <nav>
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'auth_pos:cashier_dashboard' %}">Home</a></li>
            <li class="breadcrumb-item active"><a href="{% url 'pos:sale_list' %}">All Sales</a></li>
          </ol>
        </nav>
    </div>
    <!-- End Page Title -->

    <section class="section profile">
        <div class="row">
            <div class="col-12 col-md-12 col-lg-12 col-xl-12">
                <div class="card border-left-success shadow h-100 py-2" id="cardtable">
                    <div class="card-body pt-3">
                        <!-- Bordered Tabs -->
                        <ul class="nav nav-tabs nav-tabs-bordered">
                            <li class="nav-item">
                                <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#profile-overview"> <a href="{% url 'pos:sale_list' %}">Sales</a></button>
                            </li>
                            <li class="nav-item">
                                <!-- Topbar Search -->
                                <form method="get" class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search ">
                                    <div class="input-group " id="navbarSearch">
                                        <input type="text" class="form-control bg-light  border-left-success shadow h-100 py-2 border-0 small" placeholder="Search Products..." aria-label="Search" name="search" aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-danger" type="submit">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </li>
                            <li class="nav-item">
                                <form method="get">
                                    <label for="filter_by">Filter by:</label>
                                    <select id="filter_by" name="filter_by">
                                        <option value="">All</option>
                                        <option value="today">Today</option>
                                        <option value="yesterday">Yesterday</option>
                                        <option value="this_week">This week</option>
                                        <option value="last_week">Last week</option>
                                        <option value="this_month">This month</option>
                                        <option value="last_month">Last month</option>
                                    </select>
                                    <label for="filter_date">Filter by date:</label>
                                    <input type="date" id="filter_date" name="filter_date">
                                    <label for="sort_by">Sort by:</label>
                                    <select id="sort_by" name="sort_by">
                                        <option value="">Date</option>
                                        <option value="total_amount">Total amount</option>
                                    </select>
                                    <button type="submit">Apply</button>
                                </form>
                            </li>
                        </ul>

                        <div class="tab-content pt-2">
                            <div class="tab-pane fade show active profile-overview  border-left-danger shadow h-100 py-2" id="products-overview">
                                <div class="card-body">
                                    <div class="table-responsive table-borderless table-hover table-responsive-sm table-responsive-md table-responsive-lg table-striped ">
                                        <table class="table table-hover " id="dataTable" width="100%" cellspacing="1">
                                            <thead id="tablehead">
                                                <tr>
                                                    <th>ID</th>
                                                    <th>Date</th>
                                                    <th>Cashier</th>
                                                    <th>Total</th>
                                                    <th></th>
                                                </tr>
                                            </thead>
                                            {% if sales %}
                                                <tbody>
                                                    {% for sale in sales %}
                                                        <tr>
                                                            <td>{{ sale.id }}</td>
                                                            <td>{{ sale.date }}</td>
                                                            <td>{{ sale.cashier.user }}</td>
                                                            <td>{{ sale.total_amount }}</td>
                                                            <td>
                                                                <a href="{% url 'pos:view_sale' sale.id %}" data-bs-toggle="modal" data-bs-target="#viewsale-{{ forloop.counter }}" class="btn btn-info btn-circle btn-sm">
                                                                    <i class="fas fa-pencil" ></i><i class="fa-solid fa-pencil"></i>
                                                                </a>
                                                            </td>
                                                        </tr>
                                                    {% endfor %}
                                                </tbody>

                                            {% else %}
                                                <tbody>
                                                    <tr>
                                                        <td colspan="9" class="text-center">
                                                            No sales Found ! <b>You have to sell products for the sales to appear </b>
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            {% endif %}
                                        </table>
                                    </div>

                                    <nav aria-label="Page navigation example" class="mt-4">
                                        <ul class="pagination  justify-content-end">
                                            {% if sales.has_previous %}
                                                <li class="page-item">
                                                    <a class="page-link" href="?page={{ sales.previous_page_number }}&filter_by={{ filter_by }}&filter_date={{ filter_date }}&sort_by={{ sort_by }}">Previous</a>
                                                </li>
                                            {% endif %}

                                            {% for i in sales.paginator.page_range %}
                                                {% if sales.number == i %}
                                                    <li class="page-item active">
                                                        <a class="page-link" href="?page={{ i }}&filter_by={{ filter_by }}&filter_date={{ filter_date }}&sort_by={{ sort_by }}">{{ i }}</a>
                                                    </li>
                                                {% else %}
                                                    <li class="page-item">
                                                        <a class="page-link" href="?page={{ i }}&filter_by={{ filter_by }}&filter_date={{ filter_date }}&sort_by={{ sort_by }}">{{ i }}</a>
                                                    </li>
                                                {% endif %}
                                            {% endfor %}

                                            {% if sales.has_next %}
                                                <li class="page-item">
                                                    <a class="page-link" href="?page={{ sales.next_page_number }}&filter_by={{ filter_by }}&filter_date={{ filter_date }}&sort_by={{ sort_by }}">Next</a>
                                                </li>
                                            {% endif %}
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                        </div><!-- End Bordered Tabs -->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End sales list -->

    {% for sale in sales %}
        <div id="viewsale-{{ forloop.counter }}" class="modal fade">
            <div class="modal-dialog modal-sm modal-dialog-centered" >
                <div class="modal-content border-left-danger shadow h-100 py-2 " id="editmodal">
                    {% for item in sale.saleitem_set.all %}
                        <div class="modal-body">
                            <h4>Sale Information | ID | {{ sale.id }} | Date | {{ sale.created_at }}</h4>
                            <p>Product: {{ item.product.name }}</p>
                            <p>Product Description: {{ item.product.description }}</p>
                            <p>Product Car Make: {{ item.product.make }}</p>
                            <p>Product Car Model: {{ item.product.model }}</p>
                            <p>Quantity: {{ item.quantity }}</p>
                            <p>Total: {{ sale.total_amount }}</p>
                        </div>
                    {% endfor  %}

                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary " data-bs-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    <!-- End view sale Modal  -->
{% endblock content %}

onedrive_pos/templates/pos/sale_table.html
<table class="table table-striped table-bordered  table-responsive  ">
    <thead id="tHead">
        <tr>
            <th>Product</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Total</th>
            <th>Catergory</th>
            <th></th>
            

        </tr>
    </thead>
    <tbody  id="sale-table-body">
        {% for item in sale_items %}
        <tr>
            <td>{{ item.product.name }}</td>
            <td><input type="number" name="quantity_{{ item.product.id }}" id="quantity_{{ item.product.id }}" value="{{ item.quantity }}" min="1" max="{{item.product.quantity}}" class="quantity-input" data-price="{{ item.product.price }}" disabled></td>
            <td >{{ item.product.price }}</td>
            <td><span id="total_{{ item.product.id }}" >{{ item.total }}</span></td>
            <td>{{ item.product.category }}</td>
            <td><a  class="btn btn-danger remove-from-sale"  data-product-id="{{ item.product.id }}"><i class="fas fa-trash"></i></a>
            </td>
            
        </tr>
        {% endfor %}
    </tbody>
</table>

onedrive_pos/templates/pos/view_sale.html
{% extends 'dashboard/cashier_dashboard.html' %}
{% block content %}
<table class="table">
    <thead>
        <tr>
            <th>Product</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        {% for item in sale.saleitem_set.all %}
        <tr>
            <td>{{ item.product.name }}</td>
            <td>{{ item.quantity }}</td>
            <td>{{ item.product.price }}</td>
            <td>{{ item.total_price }}</td>
        </tr>
        {% endfor  %}
    </tbody>
</table>
<p>Total: {{ sale.total_amount }}</p>
{% endblock %}