onedrive_pos/auth_pos/urls.py
from django.urls import path
from . import views
app_name = 'auth_pos'  # Define the namespace for URL reversal


urlpatterns = [
    #  authentication routes
    path('register/', views.register, name='register'),
    path('', views.login, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('lock_screen/', views.lock_screen, name='lock_screen'),
    path('admin_dashboard', views.admin_dashboard, name='admin_dashboard'),
    path('manager_dashboard', views.manager_dashboard, name='manager_dashboard'),
    path('cashier_dashboard', views.cashier_dashboard, name='cashier_dashboard'),
    path('loader/', views.loader_view, name='loader'),
]

onedrive_pos/onedrive_pos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    
    path('admin/', admin.site.urls),
    path('', include('auth_pos.urls')),
    path('products/', include('products.urls')),
    path('branches/', include('branches.urls')),
    path('pos/', include('pos.urls')),
    path('staff/', include('staff.urls')),
    path('profile/', include('user_profile.urls'))


]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onedrive_pos/pos/urls.py
from django.urls import path
from . import views

app_name = 'pos'

urlpatterns = [
    path('create/', views.create_sale, name='create_sale'),
    path('list/', views.sale_list, name='sale_list'),
    path('view/<int:sale_id>/', views.view_sale, name='view_sale'),
    path('search-products/', views.search_products, name='search_products'),
    path('add-product-to-sale/', views.add_product_to_sale, name='add_product_to_sale'),
    path('remove-product-from-sale/', views.remove_product_from_sale, name='remove_product_from_sale'),
    path('complete-sale/', views.complete_sale, name='complete_sale'),
    path('sales/list/', views.sales_list_view, name='sales'),
    
  
]

onedrive_pos/templates/authentication/lockscreen.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Add a meta tag to prevent the user from going back to the previous page -->
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Expires" content="0">

    <title>Lockscreen</title>
   {% include 'scripts/links.html' %}
   {% include 'scripts/scripts.html' %}
   {% load static %}

</head>
<style>
    #logo{
        margin-left:auto;
       
    }


</style>

<body class="bg-white">
    {% include 'scripts/messages.html' %}
    <div class="container">

        <!-- Outer Row -->
    <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5  border-left-danger shadow  py-2">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image">
                                {% if profile_picture.profile_pic %}
                                <div style="text-align: center;">
                                <img src="{{ profile_picture.profile_pic.url }}" alt="Profile" class="profile-picture">
                                {% else %}
                                <img src="{% static 'img\undraw_profile_1.svg' %}" alt="Default Profile Picture" class="profile-picture">
                                {% endif %}  
                            </div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-black-900 mb-4">Lockscreen</h1>
                                    </div>
                                    <form class="user" method="POST" action="{% url 'auth_pos:lock_screen' %}">
                                        {% csrf_token %}

                                        <div class="form-group">
                                            <input type="text" class="form-control form-control-user" name="username"
                                                id="exampleInputPassword" placeholder="username" required>
                                        </div>

                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user" name="password"
                                                id="exampleInputPassword" placeholder="Password" required>
                                        </div>
                                        
                                        <button  class="btn btn-danger btn-user btn-block" type="submit" ><i class="fas fa-lock-open"></i>
                                            Unlock
                                        </button>
                                       
                                        <hr>
                                       
                                    </form>
                                    <hr>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

   

</body>

</html>

onedrive_pos/templates/authentication/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title> Login</title>
   {% include 'scripts/links.html' %}
   {% include 'scripts/scripts.html' %}
   {% load static %}

</head>
{% include 'scripts/main_loader.html' %}
{% include 'scripts/messages.html' %}

<style>
    #logo{
        margin-top: 100px;
        margin-left:300px;
        width: 100px;
        height :100px;
       
    }


</style>

<body class="bg-white">
    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5  border-left-danger shadow  py-2">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image">
                                <img src="{% static 'img/logo.png' %}" alt="" id="logo">
                               
                            </div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-black-900 mb-4">Welcome Back!</h1>
                                    </div>
                                    <form class="user" method="POST" action="{% url 'auth_pos:login' %}">
                                        {% csrf_token %}

                                        <div class="form-group">
                                            <input type="text" class="form-control form-control-user" id="userName"
                                                placeholder="username" name="username" required>
                                        </div>
        
                                        
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user" name="password"
                                                id="exampleInputPassword" placeholder="Password" required>
                                        </div>
                                        <div class="form-group">
                                            <div class="custom-control custom-checkbox small">
                                                <input type="checkbox" class="custom-control-input" id="customCheck">
                                                <label class="custom-control-label" for="customCheck">Remember
                                                    Me</label>
                                            </div>
                                        </div>
                                        <button  class="btn btn-danger btn-user btn-block" type="submit" >
                                            Login
                                        </button>
                                       
                                        <hr>
                                       
                                    </form>
                                    <hr>
                                
                                    <div class="text-center">
                                        <a class="small" href="{% url 'auth_pos:register' %}">Create an Account!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

   

</body>

</html>

onedrive_pos/templates/authentication/register.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   

    <title>Register</title>

   
    {% include 'scripts/links.html' %}
    {% include 'scripts/scripts.html' %}

    

</head>

<body class="bg-gradient-primary">
    {% include 'scripts/messages.html' %}

    <div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Create an Account @OneDrive!</h1>
                            </div>
                            <form class="user" method="POST" action="{% url  'auth_pos:register' %}">
                                {% csrf_token %}
                                <div class="form-group">
                                    <input type="text" class="form-control form-control-user" id="userName"
                                        placeholder="username" name="username" required>
                                </div>

                                <div class="form-group">
                                    <input type="email" class="form-control form-control-user" id="exampleInputEmail"
                                        placeholder="Email Address" name="email" required>
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <input type="password" class="form-control form-control-user"
                                            id="exampleInputPassword" placeholder="Password" name="password" required>
                                    </div>
                                    <div class="col-sm-6">
                                        <input type="password" class="form-control form-control-user"
                                            id="exampleRepeatPassword" placeholder="Repeat Password" required>
                                    </div>
                                </div>
                                <button  class="btn btn-danger btn-user btn-block" type="submit">Register</button>
                                
                                <hr>
                               
                               
                            </form>
                            <hr>
                            <div class="text-center">
                                <a class="small" href="{% url 'auth_pos:login' %}">Already have an account? Login!</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</body>

</html>