onedrive_pos/auth_pos/urls.py
from django.urls import path
from . import views
app_name = 'auth_pos'  # Define the namespace for URL reversal


urlpatterns = [
    #  authentication routes
    path('register/', views.register, name='register'),
    path('', views.login, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('lock_screen/', views.lock_screen, name='lock_screen'),
    path('admin_dashboard', views.admin_dashboard, name='admin_dashboard'),
    path('manager_dashboard', views.manager_dashboard, name='manager_dashboard'),
    path('cashier_dashboard', views.cashier_dashboard, name='cashier_dashboard'),
    path('loader/', views.loader_view, name='loader'),
]

onedrive_pos/branches/urls.py
from django.urls import path
from . import views

app_name = 'branches'  # Define the namespace for URL reversal

urlpatterns = [


  #  branch management routes
    path('', views.branch_list, name='branch_list'),
    path('branches/create/', views.branch_create, name='branch_create'),
    path('branches/delete/<str:id>', views.branch_delete, name='branch_delete'),
    path('branches/update/<str:id>',views.branch_update, name= "branch_update"),
    path('save_update_branch',views.save_update_branch, name= "save_update_branch"),
    path('branches/<int:branch_id>/', views.branch_detail, name='branch_detail'),
    path('branch_products/<int:branch_id>/',views.branch_products, name='branch_products'),
    path('branch_products/', views.view_branch_products, name='view_branch_products'),
    path('branch_employees/', views.view_branch_employees, name='view_branch_employees'),
    path('branch/employees/<int:employee_id>/update/',views.branch_employee_update, name='branch_employee_update'),
    path('branch/employees/<int:employee_id>/delete/', views.branch_employee_delete, name='branch_employee_delete'),

    

]

onedrive_pos/onedrive_pos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    
    path('admin/', admin.site.urls),
    path('', include('auth_pos.urls')),
    path('products/', include('products.urls')),
    path('branches/', include('branches.urls')),
    path('pos/', include('pos.urls')),
    path('staff/', include('staff.urls')),
    path('profile/', include('user_profile.urls'))


]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onedrive_pos/pos/urls.py
from django.urls import path
from . import views

app_name = 'pos'

urlpatterns = [
    path('create/', views.create_sale, name='create_sale'),
    path('list/', views.sale_list, name='sale_list'),
    path('view/<int:sale_id>/', views.view_sale, name='view_sale'),
    path('search-products/', views.search_products, name='search_products'),
    path('add-product-to-sale/', views.add_product_to_sale, name='add_product_to_sale'),
    path('remove-product-from-sale/', views.remove_product_from_sale, name='remove_product_from_sale'),
    path('complete-sale/', views.complete_sale, name='complete_sale'),
    path('sales/list/', views.sales_list_view, name='sales'),
    
  
]

onedrive_pos/products/urls.py
from django.urls import path
from . import views

app_name = 'products'  # Define the namespace for URL reversal

urlpatterns = [

    #  products management routes
    path('', views.product_list, name='product_list'),
    path('upload_products_csv/', views.upload_products_csv, name='upload_products_csv'),
    path('create/', views.product_create, name='product_create'),
    path('update/<int:product_id>/', views.product_update, name='product_update'),
    path('delete/<int:product_id>/', views.product_delete, name='product_delete'),
    path('restore/<int:product_id>/', views.product_restore, name='product_restore'),
]

   

    

onedrive_pos/staff/urls.py
from django.urls import path
from . import views

app_name = 'staffs'

urlpatterns = [


    #  employee management routes
    path('', views.employee_list, name='employee_list'),
    path('employees/create/', views.employee_create, name='employee_create'),
    path('employees/<int:employee_id>/update/',views.employee_update, name='employee_update'),
    path('employees/<int:employee_id>/delete/', views.employee_delete, name='employee_delete'),
    


   
    
]

onedrive_pos/templates/bars/sidebar.html
{% load static %}
{% include 'scripts/links.html' %}
{% include 'scripts/scripts.html' %}


<style>

    #accordionSidebar{

        background-color: rgb(206, 96, 114);
    }
    #logo{
        width: 80px;
        height: 80px;
    }


</style>


<ul class="navbar-nav bg-gradient sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="">
        <div class="sidebar-brand-icon ">
            <img src="{% static 'img/logo.png' %}" alt="" id="logo">
            
        </div>
        <div class="sidebar-brand-text mx-3">OneDrive</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

{% if user.is_authenticated   %}
    <!-- Nav Item - Dashboard -->
    {% if user.role == 'admin' %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'auth_pos:admin_dashboard' %}">
            <i class="fas fa-fw fa-tachometer-alt fa-3x text-black-400"></i>
            <span> Admin Dashboard</span></a>
    </li>
    {% elif user.role == 'manager' %}
       <!-- Nav Item - Dashboard -->
       <li class="nav-item active">
        <a class="nav-link" href="{% url 'auth_pos:manager_dashboard' %}">
            <i class="fas fa-fw fa-tachometer-alt fa-3x text-black-400"></i>
            <span>Manager Dashboard</span></a>
    </li>
    {% else %}
      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'auth_pos:cashier_dashboard' %}">
            <i class="fas fa-fw fa-tachometer-alt fa-3x text-black-400"></i>
            <span>POS</span>
            <span>{{branch.name}}</span>
        </a>
    </li>
    {% endif %}
{% endif %}




    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Interface
    </div>


{% if user.is_authenticated   %}
    <!-- Nav Item - Pages Collapse Menu -->
    {% if user.role == 'admin' %}
    <li class="nav-item {% if active_nav_item == 'products' %}active{% endif %}">
        <a class="nav-link collapsed" href="{% url 'products:product_list' %}"
            aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-car fa-3x text-black-400"></i>
            <span>Products Management</span>
        </a>
        
    </li>

    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item {% if active_nav_item == 'branches' %}active{% endif %}">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
            aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-building fa-3x text-black-400"></i>
            <span>Branch Management</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
            data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="{% url 'branches:branch_list' %}">Branches</a>
                
            </div>
        </div>
    </li>

    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item {% if active_nav_item == 'staff' %}active{% endif %}">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
            aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-people-carry fa-3x text-black-400"></i>
            <span>Staff Management</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
            data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="{% url 'staffs:employee_list' %}">Members</a>
            </div>
        </div>
    </li>

     <!-- Nav Item - Utilities Collapse Menu -->
     <li class="nav-item {% if active_nav_item == 'sales' %}active{% endif %}">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
            aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-calendar fa-3x text-black-400"></i>
            <span>Reports and Analytics</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
            data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="{% url 'pos:sales' %}">Sales Reports</a>
                <a class="collapse-item" href="#">Inventory Reports</a>
            </div>
        </div>
    </li>

    {% elif user.role == 'manager' %}
    <li class="nav-item {% if active_nav_item == 'branches' %}active{% endif %}">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
            aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-building fa-3x text-black-400"></i>
            <span>Branch Management </span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="{% url 'branches:view_branch_products' %}">Branch Products</a>
                <a class="collapse-item" href="#">Branch Customers</a>
                <a class="collapse-item" href="#">Branch Reports</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item {% if active_nav_item == 'staff' %}active{% endif %}">
        <a class="nav-link collapsed" href="{% url 'branches:view_branch_employees' %}" 
            aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-people-carry fa-3x text-black-400"></i>
            <span>Branch Staff Management</span>
        </a>
       
    </li>

   

     <!-- Nav Item - Utilities Collapse Menu -->
     <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
            aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-calendar fa-3x text-black-400"></i>
            <span>Reports and Analytics</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
            data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="#">Branch Sales Reports</a>
                <a class="collapse-item" href="#">BranchInventory Reports</a>
            </div>
        </div>
    </li>


    {% else %}
    <li class="nav-item {% if active_nav_item == 'pos' %}active{% endif %}">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
            aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-shopping-cart"></i>
            <span>Sales</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="{% url 'pos:create_sale' %}">New Sale</a>
                <a class="collapse-item" href="{% url 'pos:sale_list' %}">Sales List</a>
                <a class="collapse-item" href="#">Sales Reports</a>
                
            </div>
        </div>
    </li>

    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item {% if active_nav_item == 'products' %}active{% endif %}">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
            aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Products</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
            data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="#">Product Search</a>
            </div>
        </div>
    </li>

   

     <!-- Nav Item - Utilities Collapse Menu -->
     <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
            aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Reports and Customers</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
            data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="#">Branch Customers</a>
                <a class="collapse-item" href="#">Sales by Product</a>
                <a class="collapse-item" href="#">Sales by Customer</a>
            </div>
        </div>
    </li>
    {% endif %}




    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Settings
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'profile:profile_detail' user.pk %}"
            aria-expanded="true" aria-controls="collapsePages">
            <i class="fas fa-user fa-3x text-black-400"></i>
            <span>Profile</span>
        </a>
       
    </li>



    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>


    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">

        <!-- Logout button -->
        <a href="" data-bs-toggle="modal" data-bs-target="#logoutModal" 
        class="btn btn-danger btn-circle btn-sm"><i class="fas fa-sign-out-alt"></i>Logout
      </a>
 
    </div>



    <!-- Logout modal -->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="logoutModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="logoutModalLabel">Logout Confirmation</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Your session will be closed in 5 seconds.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <a href="{% url 'auth_pos:logout' %}" class="btn btn-primary">Logout</a>
            </div>
        </div>
    </div>
</div>


<script>
    var lockScreenUrl = "{% url 'auth_pos:lock_screen' %}";
    $('#logoutModal').on('shown.bs.modal', function () {
        var count = 5;
        var counter = setInterval(function() {
            count--;
            document.getElementById("timer").innerHTML = "Your session will be closed in " + count + " seconds.";
            if (count === 0) {
                clearInterval(counter);
                $('#logoutModal').modal('hide');
                window.location.href = lockScreenUrl;
            }
        }, 1000);
    });
</script>










{% endif  %}

  

</ul>

onedrive_pos/templates/bars/topbar.html
{% load static %}
{% include 'scripts/links.html' %}
{% include 'scripts/scripts.html' %}

 <!-- Topbar -->
 <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Search -->
    <form
        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
        <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small"
                            placeholder="Search for..." aria-label="Search"
                            aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>


        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{user.username}}</span>
                <img class="img-profile rounded-circle"
                    src="img/undraw_profile.svg">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Profile
                </a>
               
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                </a>
            </div>
        </li>

    </ul>

</nav>
<!-- End of Topbar -->