onedrive_pos/auth_pos/urls.py
from django.urls import path
from . import views
app_name = 'auth_pos'  # Define the namespace for URL reversal


urlpatterns = [
    #  authentication routes
    path('register/', views.register, name='register'),
    path('', views.login, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('lock_screen/', views.lock_screen, name='lock_screen'),
    path('admin_dashboard', views.admin_dashboard, name='admin_dashboard'),
    path('manager_dashboard', views.manager_dashboard, name='manager_dashboard'),
    path('cashier_dashboard', views.cashier_dashboard, name='cashier_dashboard'),
    path('loader/', views.loader_view, name='loader'),
]

onedrive_pos/branches/urls.py
from django.urls import path
from . import views

app_name = 'branches'  # Define the namespace for URL reversal

urlpatterns = [


  #  branch management routes
    path('', views.branch_list, name='branch_list'),
    path('branches/create/', views.branch_create, name='branch_create'),
    path('branches/delete/<str:id>', views.branch_delete, name='branch_delete'),
    path('branches/update/<str:id>',views.branch_update, name= "branch_update"),
    path('save_update_branch',views.save_update_branch, name= "save_update_branch"),
    path('branches/<int:branch_id>/', views.branch_detail, name='branch_detail'),
    path('branch_products/<int:branch_id>/',views.branch_products, name='branch_products'),
    path('branch_products/', views.view_branch_products, name='view_branch_products'),
    path('branch_employees/', views.view_branch_employees, name='view_branch_employees'),
    path('branch/employees/<int:employee_id>/update/',views.branch_employee_update, name='branch_employee_update'),
    path('branch/employees/<int:employee_id>/delete/', views.branch_employee_delete, name='branch_employee_delete'),

    

]

onedrive_pos/onedrive_pos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    
    path('admin/', admin.site.urls),
    path('', include('auth_pos.urls')),
    path('products/', include('products.urls')),
    path('branches/', include('branches.urls')),
    path('pos/', include('pos.urls')),
    path('staff/', include('staff.urls')),
    path('profile/', include('user_profile.urls'))


]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onedrive_pos/pos/urls.py
from django.urls import path
from . import views

app_name = 'pos'

urlpatterns = [
    path('create/', views.create_sale, name='create_sale'),
    path('list/', views.sale_list, name='sale_list'),
    path('view/<int:sale_id>/', views.view_sale, name='view_sale'),
    path('search-products/', views.search_products, name='search_products'),
    path('add-product-to-sale/', views.add_product_to_sale, name='add_product_to_sale'),
    path('remove-product-from-sale/', views.remove_product_from_sale, name='remove_product_from_sale'),
    path('complete-sale/', views.complete_sale, name='complete_sale'),
    path('sales/list/', views.sales_list_view, name='sales'),
    
  
]

onedrive_pos/staff/urls.py
from django.urls import path
from . import views

app_name = 'staffs'

urlpatterns = [


    #  employee management routes
    path('', views.employee_list, name='employee_list'),
    path('employees/create/', views.employee_create, name='employee_create'),
    path('employees/<int:employee_id>/update/',views.employee_update, name='employee_update'),
    path('employees/<int:employee_id>/delete/', views.employee_delete, name='employee_delete'),
    


   
    
]

onedrive_pos/branches/models.py
from django.db import models

#  branch model
class Branch(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=255)
    is_deleted = models.BooleanField(default=False)

    def delete(self):
        self.is_deleted = True
        self.save()

    def __str__(self):
        return self.name

onedrive_pos/branches/views.py
from django.shortcuts import render
from django.shortcuts  import render 
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from .models import *
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from products.models import Product, Category
from staff.models import Employee
from  pos.models import Sale
from django.db.models import Count, Sum
from django.http import HttpResponse




# Branch management  CRUD views
@login_required
@user_passes_test(lambda user: user.has_perm('main.view_branch_list'))
def branch_list(request):
    active_nav_item = 'branches'
    try:
        branches = Branch.objects.filter(is_deleted=False)
        return render(request, 'branches/branches.html', {'branches': branches,'active_nav_item':active_nav_item})
    except Exception as e:
        messages.error(request, 'Error fetching branches: {}'.format(e))
        return redirect('branches:branch_list',{'active_nav_item':active_nav_item})

@login_required
@user_passes_test(lambda user: user.has_perm('main.add_branch'))
def branch_create(request):
    active_nav_item = 'branches'
    if request.method == 'POST':
        name = request.POST.get('name')
        location = request.POST.get('location')

        # Validate input
        if not location or not name:
            messages.error(request, 'Please fill in all fields')
            return render(request, 'branches/branches.html')

        try:
            Branch.objects.create(name=name, location=location)
            messages.success(request, 'Branch created successfully!')
            return redirect('branches:branch_list')  # Redirect to branch list after success
        except Exception as e:
            messages.error(request, 'Error creating branch: {}'.format(e))
            return render(request, 'branches/branches.html')
    return render(request, 'branches/branches.html',{'active_nav_item':active_nav_item})

@login_required
@user_passes_test(lambda user: user.has_perm('main.update_branch'))
def branch_update(request):
    active_nav_item = 'branches'
    try:
        branch = Branch.objects.get(id=request.GET.get('id'))
        context = {'branch': branch,
                   'active_nav_item':active_nav_item,
                   }
        return render(request, 'branches/branches.html', context)
    except Branch.DoesNotExist:
        messages.error(request, 'Branch not found')
        return redirect('branches:branch_list')

@login_required
@user_passes_test(lambda user: user.has_perm('main.update_branch'))
def save_update_branch(request):
    active_nav_item = 'branches'
    if request.method == 'POST':
        try:
            branchid = request.POST.get('id')
            branch = Branch.objects.get(id=branchid)
            branch.name = request.POST.get('name')
            branch.location = request.POST.get('location')
            branch.save()
            messages.success(request, 'Branch updated successfully!')
            return redirect('branches:branch_list',{'active_nav_item':active_nav_item})
        except Exception as e:
            messages.error(request, 'Error updating branch: {}'.format(e))
            return render(request, 'branches/branches.html')

@login_required
@user_passes_test(lambda user: user.has_perm('main.delete_branch'))
def branch_delete(request, id):
    try:
        branch = Branch.objects.get(id=id)
        if branch.product_set.exists():
            messages.error(request, 'Cannot delete branch with products. Please delete or transfer products first.')
            return redirect('branches:branch_list')
        else:
            branch.delete()  # Use the custom delete method
            messages.success(request, 'Branch deleted successfully!')
            return redirect('branches:branch_list')
    except Branch.DoesNotExist:
        messages.error(request, 'Branch not found')
        return redirect('branches:branch_list')

@login_required
@user_passes_test(lambda user: user.has_perm('main.view_branch_list'))
def branch_detail(request, branch_id):
    active_nav_item = 'branches'
    try:
        branch = Branch.objects.get(id=branch_id)
        products_count = Product.objects.filter(branch=branch).count()
        employees_count = Employee.objects.filter(branch=branch).count()
        sales_count = Sale.objects.filter(branch=branch).count()
        revenue = Sale.objects.filter(branch=branch).aggregate(total_revenue=Sum('total'))['total_revenue']

        context = {
            'active_nav_item':active_nav_item,
            'branch': branch,
            'products_count': products_count,
            'employees_count': employees_count,
            'sales_count': sales_count,
            'revenue': revenue,
        }
        return render(request, 'branches/branches.html', context)
    except Branch.DoesNotExist:
        messages.error(request, 'Branch not found')
        return redirect('branches:branch_list')


@login_required
@user_passes_test(lambda user: user.has_perm('main.view_branch_list'))
def view_branch_products(request):
    active_nav_item = 'branches'
    if request.user.role == 'manager':
        branch = request.user.employee.branch
        products = Product.objects.filter(branch=branch)
        product_count = products.count()

        # Get the search query from the GET parameters
        search_query = request.GET.get('search', '')

        # Filter products based on the search query
        if search_query:
            products = products.filter(
                Q(name__icontains=search_query) |
                Q(description__icontains=search_query) |
                Q(make__icontains=search_query) |
                Q(model__icontains=search_query) |
                Q(price__icontains=search_query) |
                Q(category__name__icontains=search_query)  # Added category field
            )

        # Filter products by category
        category_id = request.GET.get('category')
        if category_id:
            products = products.filter(category_id=category_id)

        # Paginate the filtered and ordered products

        page_size = 10 
        paginator = Paginator(products.order_by('name'), page_size)

        page = request.GET.get('page')
        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)

        context = {
            'active_nav_item':active_nav_item,
            'paginator': paginator,
            'products': products,
            'search_query': search_query,
            'product_count': product_count,
            'categories': Category.objects.all(),  # Pass categories for filtering
        }
        return render(request, 'branches/branch_based_products.html', context)
    else:
        return redirect('auth_pos:login')


@login_required
@user_passes_test(lambda user: user.has_perm('main.view_branch_list'))
def view_branch_employees(request):
    active_nav_item = 'staff'
    if request.user.role == 'manager':
        branch = request.user.employee.branch
        employees = Employee.objects.filter(branch=branch)
        branches = Branch.objects.all()

        employee_count = employees.count()
        context = {
            'active_nav_item':active_nav_item,
            'branch': branch,
            'employees': employees,
            'employee_count': employee_count,
            'branches': branches,
        }
        return render(request, 'branches/branch_employees.html', context)
    else:
        return redirect('auth_pos:login')

@login_required
@user_passes_test(lambda user: user.has_perm('main.update_employee'))
def branch_employee_update(request, employee_id):
    active_nav_item = 'staff'
    employee = Employee.objects.get(pk=employee_id)
    if request.method == 'POST':
        email = request.POST.get('email')
        role = request.POST.get('role')

        try:
            employee.user.username = request.POST.get('username')
            employee.user.role = role
            employee.user.email = email
            employee.user.save()
            employee.save()
            messages.success(request, 'Employee updated successfully!')
            return redirect('branches:view_branch_employees')
        except Exception as e:
            messages.error(request, 'Error updating employee: {}'.format(e))
    else:
        branches = Branch.objects.all()
        return render(request, 'branches/branch_employees.html', {'employee': employee, 'branches': branches,'active_nav_item':active_nav_item})

@login_required
@user_passes_test(lambda user: user.has_perm('main.delete_employee'))
def branch_employee_delete(request, employee_id):
    active_nav_item = 'staff'
    employee = Employee.objects.get(pk=employee_id)
    employee.delete()
    messages.success(request, 'Employee deleted successfully!')
    return redirect('branches:view_branch_employees',{'active_nav_item':active_nav_item})


@login_required
@user_passes_test(lambda user: user.has_perm('main.view_branch_list'))
def branch_products(request, branch_id):
    active_nav_item = 'branches'
    
    try:
        branch = Branch.objects.get(id=branch_id)
        products = branch.product_set.select_related('branch')
        branch_products_count = products.count()

        # Get the search query from the GET parameters
        search_query = request.GET.get('search', '')

        # Filter products based on the search query
        if search_query:
            products = products.filter(
                Q(name__icontains=search_query) |
                Q(description__icontains=search_query) |
                Q(make__icontains=search_query) |
                Q(model__icontains=search_query) |
                Q(price__icontains=search_query) |

onedrive_pos/templates/branches/branches.html
{% extends 'dashboard/admin_dashboard.html' %}
{% block content %}


{% include 'scripts/main_loader.html' %}
<!-- page title -->
<div class="pagetitle">
    <h1 class="h5 text-md font-weight-bold text-primary text-uppercase mb-1">Branches</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'auth_pos:admin_dashboard' %}">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'branches:branch_list' %}">Branches</a></li>
      </ol>
    </nav>
</div><!-- End Page Title -->


{% include 'scripts/messages.html' %}


<!-- page indoc styling  -->
<style>

    .breadcrumb{

        background-color: white;
        border-radius: 30px;
    }
    .btn{
      margin-top: 5px;
      

    }

    .pagetitle{
        margin-top: 40px;
        margin-right: 20px;
        margin-left: 20px;
        


    }
    #noBranchCard{

        border-radius: 30px;
        margin-bottom: 20px;


    }



    #branchMainCard{

        margin-bottom: 30px;
        border-radius: 30px;
        margin-left: 20px;
        margin-right: 20px;
        


    }
    #BranchCard{

        margin-top: 30px;
        margin-left: 30px;
        margin-right: 30px;
        margin-bottom: 30px;

    }
    #addbranchBtn{

        
        margin-right: 30px;
        margin-left: 30px;
        margin-top: 30px;
        margin-bottom: 30px;
        


    }
    input[type="text"] {
      margin-bottom: 10px;
      margin-right: auto;
      
      margin-top: auto;
      width: auto;
      
      /* Styles for text input elements */
  }
  
  input[type="number"] {
    margin-bottom: 10px;
    margin-right: auto;
    margin-left: auto;
    margin-top: auto;
    width: fit-content;
    
    /* Styles for text input elements */
  }
  input[type="password"] {
      margin-bottom: 10px;
      margin-right: auto;
      margin-left: auto;
      margin-top: auto;
      width: fit-content;
      
      /* Styles for text input elements */
    }
    input[type="email"] {
      margin-bottom: 10px;
      margin-right: auto;
      margin-left: auto;
      margin-top: auto;
      width: fit-content;
      
      /* Styles for text input elements */
    }
  input[type="option"] {
    margin-bottom: 10px;
    margin-right: auto;
    margin-left: auto;
    margin-top: auto;
    width: fit-content;
    
    /* Styles for text input elements */
  }
  input[type="file"] {
    margin-bottom: 10px;
    margin-right: auto;
    margin-left: auto;
    margin-top: auto;
    color: #333;
    width: fit-content;
    
    /* Styles for text input elements */
  }
   

.form-control {
  border: 0;
  border-bottom: 1px solid rgb(206, 96, 114);
  border-radius: 0;
  padding: 8px;
  margin-left: auto;
  
}
.form-control:focus {
  
  box-shadow: none;
}

.floating-input {
  padding-top: 10px;
  padding-bottom: 10px;
}

.floating-input:focus, .floating-input:not(:placeholder-shown) {
  padding-top: 0;
  padding-bottom: 0;
}

.floating-input:not(:placeholder-shown) + label {
  position: absolute;
  top: -12px;
  left: 0;
  font-size: 80%;
  color: #777;
}

label {
  margin-left:40px;
  
  font-weight: bold;
  color: #333;
}
.custom-select {
  /* Your styles here */
  border: 1px solid #bd4242;
  padding: 5px;
  border-radius: 10px;
  width: auto;
  margin-left: 20px;
  
}
.custom-select:focus {
  border: 0;
    border-bottom: 1px solid rgb(206, 96, 114);
    border-radius: 0;
    padding: 8px;
  
}
.btn{
  margin-top: 5px;
  

}


  
  
#navbarSearch{
      margin-top: 5px;
      margin-left: 2px
    }
.nav-item{
      margin-right: 5px;
}
#tablehead{
  
      background-color: rgb(206, 96, 114);
      color: white
}
#productqty{
      font-size: large;
}
#product_name{
      border-radius: 60px;
}
.user{
border-radius: 30px;
    }


   
#branchfooter{

    justify-items: center;
    

    align-content: center;
  }
#edittitle{

  margin-left: 5px;
}
  
   

</style>
<!-- end styling -->



{% if messages %}
    {% with message=messages.first %}
        <script>
            Swal.fire({
                title: '{{ message.tags }}',
                text: '{{ message }}',
                icon: '{{ message.tags }}' == 'success' ? 'success' : 'error'
            });
        </script>
    {% endwith %}
{% endif %}

<!-- branch list in cards -->
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
<div class="card  border-left-success shadow h-100 py-2" id="branchMainCard">
  <div id="branchlistbtns">
    <a href="#"  data-bs-toggle="modal" id="addbranchBtn" data-bs-toggle="modal" data-bs-target="#branchModal" class="btn btn-primary btn-icon-split">
      <span class="icon text-white-50">
          <i class="fas fa-plus"></i>
      </span>
      <span class="text">Branch</span>
  </a>
  </div>
  {% if  not branches %}
  <div class="col-lg-12">
    <div class="card bg-warning" id="noBranchCard">
      <div class="card-body">
        <h5 class="card-title">No Branches found!</h5>
        <p class="card-text">You can add a new branch by clicking on the "<b><i class="fas fa-plus"></i>Add Branch</b>" button.</p>
      </div>
    </div>
  </div>
  {% else %}
  <div class="row">
    {% for branch in branches %}
      <div class="col-xl-3 col-md-6 mb-4" id="BranchCard">
        <div class="card border-left-danger shadow h-100 py-2">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Name: <b>{{ branch.name }}</b></div>
                <div class="h5 mb-0 font-weight-bold text-black-800">location: <b>{{ branch.location }}</b></div>
              </div>
              <div class="col-auto">
                <i class="fas fa-building fa-2x text-black-300"></i>
              </div>
            </div>
          </div>
          <div class="card-footer " id="branchfooter">
            <button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#viewDetailsModal{{ branch.id }}">Details</button>
            <a href="{% url 'branches:branch_products' branch.id %}"  class="btn btn-success btn-sm" >Inventory</a>
            <a href="{% url 'branches:branch_update' branch.id %}" data-bs-toggle="modal" data-bs-target="#editBranch-{{forloop.counter}}" class="btn btn-warning btn-sm">Edit</a>
            <a href="{% url 'branches:branch_delete' branch.id %}" data-bs-toggle="modal" data-bs-target="#deleteBranch-{{forloop.counter}}" class="btn btn-danger btn-sm">Delete</a>
         
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
  {% endif %}
</div>
</div>
<!-- end branch list -->



<!-- branch details  modal -->
{% for branch in branches %}
<div class="modal fade" id="viewDetailsModal{{ branch.id }}" tabindex="-1" >
  <div class="modal-dialog  modal-sm modal-dialog-centered" role="document">
    <div class="modal-content">
        <div class="modal-header" >
          <button type="button" class="close" data-bs-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
          <div class="modal-body">
            <h4>Branch Information</h4>
            <p>Name: {{ branch.name }}</p>
            <p>Location: {{ branch.location }}</p>

            <h4>Branch Statistics</h4>
            <p>Products Count: {{ products_count }}</p>
            <p>Employees Count: {{ employees_count }}</p>
            <p>Sales Count: {{ sales_count }}</p>
        
            <p>Revenue: {{ revenue }}</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
          </div>
         
    </div>
   
  </div>
</div>
{% endfor %}
<!-- end branch deatils modal -->




<!-- branch creation modal -->
<div class="modal fade" id="branchModal" tabindex="-1" >
      <div class="modal-dialog  modal-sm modal-dialog-centered" role="document">
        <div class="modal-content  border-left-danger shadow  py-2">
          <div class="modal-header text-center justify-content-center">						
            <h4 class="modal-title justify-content-center text-center "><span class="badge badge-primary">Add Branch</span></h4>
            <button type="button" class="close" data-bs-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
          <!-- branch creation form -->
          <div class="modal-body"  >
            <form class="user" method="POST" action="{% url 'branches:branch_create' %}" id="branchform">
                {% csrf_token %}
                    
                <div class="modal-body">		
                    <div class="form-group">
                        <label>Branch Name</label>
                        <input type="text" class="form-control floating-input" name="name"  required>
                        
                    </div>
                    <div class="form-group">
                      <label>Branch Location</label>
                      <input type="text" class="form-control floating-input" name="location"  required>
                     
                  </div> 
                </div>   
            </form>
          </div>
          <div class="modal-footer text-center justify-content-center"  >
            <button  class="btn btn-primary btn-user " type="submit"  form="branchform">
              Create Branch
          </button>  
            <button type="button" class="btn btn-danger " data-bs-dismiss="modal">
              Close</button>
          </div>
        </div>
      </div>
</div>
<!-- end branch creation modal -->



<!-- Edit branch Modal HTML -->
 {% for branch in branches %}
<div id="editBranch-{{forloop.counter}}" class="modal fade">
    <div class="modal-dialog  modal-sm modal-dialog-centered">
        <div class="modal-content  border-left-danger shadow  py-2">
            <form method="POST" action="{% url 'branches:save_update_branch'  %}" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="modal-header justify-content-center text-center">						
                    <h4 class="modal-title " id="edittitle"><span class="badge badge-success">Update <br> <b>{{branch.name}}'s <br> Details</b></span></h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">					
                    <div class="form-group">
                        <label>Name</label>
                        <input type="text" class="form-control floating-input" name="name" value="{{ branch.name }}" required>
                        <input type="text" class="form-control" name="id" value="{{ branch.id }}" hidden>
                    </div>
                    <div class="form-group">
                        <label>Location</label>
                        <input type="text" class="form-control floating-input"  name='location' value="{{ branch.location }}" required>
                    </div>			
                </div>
                <div class="modal-footer justify-content-center">
                    <input type="button" class="btn btn-primary" data-bs-dismiss="modal" value="Cancel">
                    <input type="submit" class="btn btn-info" value="Save" >
                </div>
            </form>
        </div>
    </div>
</div>
{% endfor %}
<!-- end edit branch modal -->


<!-- Delete Branch Modal HTML -->
{% for branch in branches %}
<div id="deleteBranch-{{forloop.counter}}" class="modal fade">
    <div class="modal-dialog modal-dialog-centered  modal-sm ">
        <div class="modal-content  border-left-danger shadow  py-2">
            <form action="{% url 'branches:branch_delete' branch.id %}" method="post">
                {% csrf_token %}
                <div class="modal-header justify-content-center">						
                    <h4 class="modal-title"><span class="badge badge-warning">Delete <br><b>{{branch.name}} </b></span></h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body text-center">					
                    <p>Are you sure you want to delete this branch</p>
                    <p class="text-warning text-center"><small>This action cannot be undone.</small></p>
                </div>
                <div class="modal-footer text-center justify-content-center">
                    <input type="button" class="btn btn-primary" data-bs-dismiss="modal" value="Cancel">
                    <input type="submit" class="btn btn-danger" value="Delete">
                </div>
            </form>
        </div>
    </div>
</div>
{% endfor %}
<!-- end delete branch modal -->
  

{% endblock content%}